import iconItems from "./Icons/icons";
import storySlider from "./storySlider/storySlider";
import categorizeShopping from "./categorizeShopping/categorizeShopping";
import clientTaste from "./clientTaste/clientTaste";
import clientTaste2 from "./clientTaste2/clientTaste2";
import mostPopularBrands from "./mostPopularBrand/mostPopularBrand";
import partnerShip from "./partnerShip/partnerShip";
import partnerShip2 from "./partnerShip/partnerShip2";
import partnerShip3 from "./partnerShip/partnerShip3";
import partnerShip4 from "./partnerShip/partnerShip4";
import selectedOffer from "./selectedOffer/selectedoffer";
import readingBlog from "./raedingBlog/readingBlog";
import mostSell from "./mostSell/mostSell";
import countDown from "./header/banner";
import mainSlider from "./mainSlider/mainSlider";
import superMarket from "./superMarket/superMarket";
import goToTopButton from "./footer/backToTopBTN";
import features from "./footer/features";
import withDigikala from "./footer/withDigikala";
import customer from "./footer/customer";
import guide from "./footer/guide";
import amazingSlider from "./amazingSlider/amazingSlider";

iconItems();
storySlider();
categorizeShopping();
clientTaste();
clientTaste2();
mostPopularBrands();
partnerShip();
partnerShip2();
partnerShip3();
partnerShip4();
selectedOffer();
readingBlog();
mostSell();
setInterval(() => {
  countDown();
}, 1000);
mainSlider();
superMarket();
goToTopButton();
features();
withDigikala();
customer();
guide();
amazingSlider();
